#!/bin/bash
set -e -o pipefail

echo "* Installing Ruby"

# Nuke all Ruby gems, to drop whatever environment we had before
echo -e "\n* Nuking gems"
rm -rf ~/.gem

echo -e "\n* Installing Ruby"
sudo apt install -y ruby ruby-bundler
# to update openssl gem, you need to build C stuff from scratch and that requires ruby.h and other deps
sudo apt install -y ruby-dev libssl-dev

echo -e "\n* Configuring gem folder to ~/.gem"
# This will be honored not just by `bundler`, but also by `gem`
bundle config set --global path ~/.gem

echo -e "\n* Updating gems"
gem update

