#!/bin/bash
set -e -o pipefail

echo "* Nuking any existing NeoVim configuration"

# Nuke any existing neovim configuration
# neovim config files, here the lazyvim git repo is cloned
rm -rf ~/.config/nvim
# Some lua-related stuff
rm -rf ~/.cache/nvim
# All plugins, gems and lua stuff goes here
rm -rf ~/.local/share/nvim
# lazyvim/nvim logs go here
rm -rf ~/.local/state/nvim

# Nuke all Ruby gems
rm -rf ~/.gem

# Install basic tools
echo -e "\n* Installing basic tools"
sudo apt install git -y

# LazyGit is awesome
echo -e "\n* Installing lazygit"
sudo apt install lazygit -y

# Install basic lazyvim dependencies
echo -e "\n* Installing basic lazyvim dependencies"
sudo apt install fzf ripgrep fd-find -y

# Install neovim. Need to install the one from snap:
# apt-based is older and lazyvim requires 0.11+
echo -e "\n* Installing NeoVim"
sudo apt autoremove --purge neovim
sudo snap install nvim --classic

# Probably necessary for Lua (used heavily by LazyVim)?
# Fixes Lua-related Query Error: "substitute"
echo -e "\n* Installing luarocks"
sudo apt install luarocks -y

# Needed to install Ruby-related gems such as "ruby-lsp"
# The reason is that Mason will install the gem into its own folder, which causes the gem and all deps to be installed,
# some of the deps require native extensions.
sudo apt install build-essential -y

./install-term

# Install Ruby - not strictly necessary for LazyGit, but
# I want to set up Ruby LazyVim dev env.
# We'll setup Mise, then install Ruby via mise
# https://mise.jdx.dev/installing-mise.html

if [[ ! -e "/usr/bin/mise" ]]; then
  echo -e "\n* Installing Mise"

  sudo apt update -y && sudo apt install -y gpg sudo wget curl
  sudo install -dm 755 /etc/apt/keyrings
  wget -qO - https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | sudo tee /etc/apt/keyrings/mise-archive-keyring.gpg 1>/dev/null
  echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main" | sudo tee /etc/apt/sources.list.d/mise.list
  sudo apt update
  sudo apt install -y mise

  echo 'mise activate fish | source' >>~/.config/fish/config.fish
fi

echo -e "\n* Installing Ruby"
# To build Ruby, you need couple of things
sudo apt install -y zlib1g-dev libffi-dev libyaml-dev
mise use --global ruby

# Also Fixes Lua-related Query Error: "substitute"
echo -e "\n* Installing nodejs"

# nodejs in apt is older; also npm comes with tons of dependencies. It's easier to install & update it via mise
#sudo apt install nodejs
mise use --global node

# Configure LazyVim according to https://www.lazyvim.org/installation
echo -e "\n* Configuring NeoVim for LazyVim"
git clone https://github.com/LazyVim/starter ~/.config/nvim

# Done!
echo -e "\n* Done. Now:"
echo "- Close this terminal and open a new one (Alacritty), so that Mise activates"
echo "- (Optional) uninstall gnome-terminal and only keep Alacritty"
echo "- Run nvim from the Alacritty terminal"
echo "- Once everything installs, run :LazyHealth"
echo "- Install LazyVim/Ruby: open Lazy Extras and install lang.ruby. More info: https://www.lazyvim.org/extras/lang/ruby"
