#!/bin/bash
set -e -o pipefail

echo "* Installing Ruby"

# Nuke all Ruby gems, to drop whatever environment we had before
rm -rf ~/.gem

# Needed to install Ruby-related gems such as "ruby-lsp"
# The reason is that Mason will install the gem into its own folder, which causes the gem and all deps to be installed,
# some of the deps require native extensions.
sudo apt install build-essential -y

# We'll setup Mise, then install Ruby via mise
# https://mise.jdx.dev/installing-mise.html

if [[ ! -e "/usr/bin/mise" ]]; then
  echo -e "\n* Installing Mise"

  sudo apt update -y && sudo apt install -y gpg sudo wget curl
  sudo install -dm 755 /etc/apt/keyrings
  wget -qO - https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | sudo tee /etc/apt/keyrings/mise-archive-keyring.gpg 1>/dev/null
  ARCH=$(dpkg --print-architecture)
  echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=$ARCH] https://mise.jdx.dev/deb stable main" | sudo tee /etc/apt/sources.list.d/mise.list
  sudo apt update
  sudo apt install -y mise

  if [[ -e "$HOME/.config/fish/config.fish" ]]; then
    # Activate Mise automatically in your Fish
    echo 'mise activate fish | source' >>~/.config/fish/config.fish
  else
    echo "Read this to activate Mise in your shell: https://mise.jdx.dev/installing-mise.html#shell-specific-installation-activation"
  fi
fi

echo -e "\n* Installing Ruby"
# To build Ruby, you need couple of things
sudo apt install -y zlib1g-dev libffi-dev libyaml-dev
mise use --global ruby
