#!/bin/bash
set -e -o pipefail

echo "* Nuking any existing NeoVim configuration"

# Nuke any existing neovim configuration
# neovim config files, here the lazyvim git repo is cloned
rm -rf ~/.config/nvim
# Some lua-related stuff
rm -rf ~/.cache/nvim
# All plugins, gems and lua stuff goes here
rm -rf ~/.local/share/nvim
# lazyvim/nvim logs go here
rm -rf ~/.local/state/nvim

# Install basic tools
echo -e "\n* Installing basic tools"
sudo apt install git -y

# LazyGit is awesome
echo -e "\n* Installing lazygit"
sudo apt install lazygit -y

# Install basic LazyVim dependencies
echo -e "\n* Installing basic LazyVim dependencies"
sudo apt install fzf ripgrep fd-find -y

# Install neovim. Need to install the one from snap:
# apt-based is older and lazyvim requires 0.11+
echo -e "\n* Installing NeoVim"
sudo apt autoremove --purge neovim
sudo snap install nvim --classic

# Probably necessary for Lua (used heavily by LazyVim)?
# Fixes Lua-related Query Error: "substitute"
echo -e "\n* Installing luarocks"
sudo apt install luarocks -y

# Install Alacritty
./install-term

# Install Ruby
./install-ruby

# Also Fixes Lua-related Query Error: "substitute"
echo -e "\n* Installing nodejs"

# Configure LazyVim according to https://www.lazyvim.org/installation
echo -e "\n* Configuring NeoVim for LazyVim"
git clone https://github.com/LazyVim/starter ~/.config/nvim

# Done!
echo -e "\n* Done. Now:"
echo "- Close this terminal and open a new one (Alacritty), so that Mise activates"
echo "- (Optional) uninstall gnome-terminal and only keep Alacritty"
echo "- Run nvim from the Alacritty terminal"
echo "- Once everything installs, run :LazyHealth"
echo "- Install LazyVim/Ruby: open Lazy Extras and install lang.ruby. More info: https://www.lazyvim.org/extras/lang/ruby"
