#!/bin/bash
set -e -o pipefail

echo "* Nuking any existing NeoVim configuration"

# Nuke any existing neovim configuration
# neovim config files, here the lazyvim git repo is cloned
rm -rf ~/.config/nvim
# Some lua-related stuff
rm -rf ~/.cache/nvim
# All plugins, gems and lua stuff goes here
rm -rf ~/.local/share/nvim
# lazyvim/nvim logs go here
rm -rf ~/.local/state/nvim

# Nuke all Ruby gems
rm -rf ~/.gem

# Install basic tools
echo -e "\n* Installing basic tools"
sudo apt install git -y

# LazyGit is awesome
echo -e "\n* Installing lazygit"
sudo apt install lazygit -y

# Install basic lazyvim dependencies
echo -e "\n* Installing basic lazyvim dependencies"
sudo apt install fzf ripgrep fd-find -y

# Install neovim. Need to install the one from snap:
# apt-based is older and lazyvim requires 0.11+
echo -e "\n* Installing NeoVim"
sudo snap install nvim --classic

# Probably necessary for Lua (used heavily by LazyVim)?
# Fixes Lua-related Query Error: "substitute"
echo -e "\n* Installing luarocks"
sudo apt install luarocks -y

# Needed to install Ruby-related gems such as "ruby-lsp"
# The reason is that Mason will install the gem into its own folder, which causes the gem and all deps to be installed,
# some of the deps require native extensions.
sudo apt install build-essential -y

# Nerd Font: downloaded from https://www.nerdfonts.com/
# Used by lazyvim a lot, for all sorts of ascii graphics, keyboard characters etc.
# You want this, otherwise lazyvim will show lots of missing characters.
# Necessary for Alacritty
if [[ ! -e "$HOME/.local/share/fonts/JetBrainsMonoNerdFont-Regular.ttf" ]]; then
  # sudo apt install fonts-jetbrains-mono   # Doesn't include Nerd Fonts
  echo -e "\n* Downloading Nerd Font"
  mkdir -p ~/.local/share/fonts
  
  curl -fLo "JetBrainsMono.zip" https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
  unzip -x JetBrainsMono.zip -d ~/.local/share/fonts/
  rm JetBrainsMono.zip
  
  # update font cache
  fc-cache -fv
  fc-list | grep -i "JetBrainsMono.*Nerd"
  
else
  echo -e "\n* Nerd Font already installed"
fi

# alacritty - recommended for lazyvim
echo -e "\n* Installing Alacritty terminal"
sudo apt install alacritty -y

# Install Alacritty themes
rm -rf ~/.config/alacritty/themes
mkdir -p ~/.config/alacritty/themes
git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes

mkdir -p ~/.config/alacritty
cat << 'EOF' >~/.config/alacritty/alacritty.toml
# https://alacritty.org/config-alacritty.html
[general]

import = ["~/.config/alacritty/themes/themes/tokyo_night.toml"]

[window]
opacity = 0.95
dimensions = { columns = 160, lines = 40 }

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }

size = 11.0

# Optional: enable ligatures (great for coding)
offset = { x = 0, y = 1 }
glyph_offset = { x = 0, y = 1 }
EOF

echo -e "\n* (Optional) Select Alacritty as the default terminal"
sudo update-alternatives --config x-terminal-emulator

# Install Ruby - not strictly necessary for LazyGit, but
# I want to set up Ruby LazyVim dev env.
# We'll setup Mise, then install Ruby via mise
# https://mise.jdx.dev/installing-mise.html

if [[ ! -e "/usr/bin/mise" ]]; then
  echo -e "\n* Installing Mise"
  
  sudo apt update -y && sudo apt install -y gpg sudo wget curl
  sudo install -dm 755 /etc/apt/keyrings
  wget -qO - https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | sudo tee /etc/apt/keyrings/mise-archive-keyring.gpg 1> /dev/null
  echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main" | sudo tee /etc/apt/sources.list.d/mise.list
  sudo apt update
  sudo apt install -y mise
  
  echo 'mise activate fish | source' >> ~/.config/fish/config.fish
fi


echo -e "\n* Installing Ruby"
# To build Ruby, you need couple of things
sudo apt install zlib1g-dev libffi-dev libyaml-dev
mise use --global ruby@3.4


# Also Fixes Lua-related Query Error: "substitute"
echo -e "\n* Installing nodejs"
#sudo apt install nodejs
mise use --global node


# Configure LazyVim according to https://www.lazyvim.org/installation
echo -e "\n* Configuring NeoVim for LazyVim"
git clone https://github.com/LazyVim/starter ~/.config/nvim

# Done!
echo -e "\n* Done. Run nvim from the Alacritty terminal; then run :LazyHealth"
echo "- Install LazyVim/Ruby: https://www.lazyvim.org/extras/lang/ruby"

