# https://alacritty.org/config-alacritty.html
[general]

import = ["~/.config/alacritty/themes/themes/catppuccin_latte.toml"]

[window]
opacity = 0.95
dimensions = { columns = 160, lines = 40 }

[font]
#normal = { family = "UbuntuMono Nerd Font Mono", style = "Regular" }
#bold = { family = "UbuntuMono Nerd Font Mono", style = "Bold" }
#italic = { family = "UbuntuMono Nerd Font Mono", style = "Italic" }
#bold_italic = { family = "UbuntuMono Nerd Font Mono", style = "Bold Italic" }
#size = 15.0

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12.0

